spring:
  datasource:
    url: jdbc:mysql://kconfdb:3306/kconf?characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: 12348765
    driver-class-name: com.mysql.jdbc.Driver
